apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdc-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /dados/brazil_data_cube/imagens